// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace projem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522060758_AddUyeYorumlari")]
    partial class AddUyeYorumlari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adminler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KullaniciAdi = "admin",
                            Sifre = "12345"
                        });
                });

            modelBuilder.Entity("Cihaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArizaAciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaksimumFiyat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumFiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Islemler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "On cam saglamsa komple panel degisimi gerekebilir; marka ve OLED/AMOLED yapisina gore fiyat degisir.",
                            Ad = "Ekran Degisimi",
                            Fiyat = 4150m,
                            Kategori = "Telefon",
                            MaksimumFiyat = 6500m,
                            MinimumFiyat = 1800m
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Pil sagligi dusen veya sisen telefonlarda parca kalitesine gore fiyat araligi degisir.",
                            Ad = "Batarya Degisimi",
                            Fiyat = 2050m,
                            Kategori = "Telefon",
                            MaksimumFiyat = 3200m,
                            MinimumFiyat = 900m
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Sarj almama ve temassizlik sorunlarinda soket temizlik veya degisim uygulanir.",
                            Ad = "Soket Tamiri",
                            Fiyat = 1450m,
                            Kategori = "Telefon",
                            MaksimumFiyat = 2200m,
                            MinimumFiyat = 700m
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Ic temizlik, baglanti kontrolleri ve genel performans taramasi iceren temel servis bakimi.",
                            Ad = "Genel Bakim",
                            Fiyat = 1050m,
                            Kategori = "Telefon",
                            MaksimumFiyat = 1500m,
                            MinimumFiyat = 600m
                        });
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SifreSifirlamaKodSonTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreSifirlamaKodu")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UyeHesabiVar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("MusteriBildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Okundu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OkunmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServisKaydiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Genel");

                    b.HasKey("Id");

                    b.HasIndex("ServisKaydiId", "Tur");

                    b.HasIndex("MusteriId", "Okundu", "OlusturmaTarihi");

                    b.ToTable("MusteriBildirimleri");
                });

            modelBuilder.Entity("ServisIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IslemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServisKaydiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IslemId");

                    b.HasIndex("ServisKaydiId", "IslemId")
                        .IsUnique();

                    b.ToTable("ServisIslemler");
                });

            modelBuilder.Entity("ServisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CihazId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FiyatCevapTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiyatOnayDurumu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Onay Gerekmez");

                    b.Property<DateTime?>("FiyatOnayTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.ToTable("ServisKayitlari");
                });

            modelBuilder.Entity("UyeYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("YoneticiGordu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "OlusturmaTarihi");

                    b.HasIndex("YoneticiGordu", "OlusturmaTarihi");

                    b.ToTable("UyeYorumlari");
                });

            modelBuilder.Entity("Cihaz", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("Cihazlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("MusteriBildirim", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("Bildirimler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServisKaydi", "ServisKaydi")
                        .WithMany("Bildirimler")
                        .HasForeignKey("ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Musteri");

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("ServisIslem", b =>
                {
                    b.HasOne("Islem", "Islem")
                        .WithMany("ServisIslemler")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServisKaydi", "ServisKaydi")
                        .WithMany("ServisIslemler")
                        .HasForeignKey("ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Islem");

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("ServisKaydi", b =>
                {
                    b.HasOne("Cihaz", "Cihaz")
                        .WithMany("ServisKayitlari")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");
                });

            modelBuilder.Entity("UyeYorum", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("Yorumlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Cihaz", b =>
                {
                    b.Navigation("ServisKayitlari");
                });

            modelBuilder.Entity("Islem", b =>
                {
                    b.Navigation("ServisIslemler");
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("Cihazlar");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("ServisKaydi", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("ServisIslemler");
                });
#pragma warning restore 612, 618
        }
    }
}
