// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace projem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adminler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KullaniciAdi = "admin",
                            Sifre = "12345"
                        });
                });

            modelBuilder.Entity("Cihaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArizaAciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Islemler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ekran Degisimi",
                            Fiyat = 2450m
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Batarya Degisimi",
                            Fiyat = 1250m
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Soket Tamiri",
                            Fiyat = 900m
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Genel Bakim",
                            Fiyat = 650m
                        });
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UyeHesabiVar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("ServisIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IslemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServisKaydiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IslemId");

                    b.HasIndex("ServisKaydiId", "IslemId")
                        .IsUnique();

                    b.ToTable("ServisIslemler");
                });

            modelBuilder.Entity("ServisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CihazId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.ToTable("ServisKayitlari");
                });

            modelBuilder.Entity("Cihaz", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("Cihazlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("ServisIslem", b =>
                {
                    b.HasOne("Islem", "Islem")
                        .WithMany("ServisIslemler")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServisKaydi", "ServisKaydi")
                        .WithMany("ServisIslemler")
                        .HasForeignKey("ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Islem");

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("ServisKaydi", b =>
                {
                    b.HasOne("Cihaz", "Cihaz")
                        .WithMany("ServisKayitlari")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");
                });

            modelBuilder.Entity("Cihaz", b =>
                {
                    b.Navigation("ServisKayitlari");
                });

            modelBuilder.Entity("Islem", b =>
                {
                    b.Navigation("ServisIslemler");
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Navigation("Cihazlar");
                });

            modelBuilder.Entity("ServisKaydi", b =>
                {
                    b.Navigation("ServisIslemler");
                });
#pragma warning restore 612, 618
        }
    }
}
